{
  "hash": "8d2c0dd0d9a6fbbaedb08c969841a4f9",
  "result": {
    "engine": "knitr",
    "markdown": "---\nauthor: Sam White\ntoc-title: Contents\ntoc-depth: 5\ntoc-location: left\ntitle: Computer Troubleshooting - Gannet Missing Storage Pool\ndate: '2024-04-23'\ndraft: false\nengine: knitr\ncategories: \n  - \"gannet\"\n  - \"Synology\"\n  - \"server\"\n  - \"2024\"\n---\n\n\n\nMost of this stuff is addressed in [this GitHub Issue](https://github.com/RobertsLab/resources/issues/1878), but here's the summary:\n\n- Received notification on 4/20/2024 from Gannet (Synology RS3618xs) that it had been disconnected from the universal power supply (UPS).\n\n- Received a second notification almost immediatley that Storage Pool 2 had crashed.\n\n- Despite not having access to some of the Synology packages, Gannet seemed to be functioning properly.\n\n- Discovered on 4/23/2024 that Gannet was in a read-only state, so restarted it. This created a worse situation where only system stuff (i.e. Disk Station Manager) was accessible; could not access any other data which had been on Storage Pool 2 (i.e. all of our data!).\n\n![Screenshot of Storage Manager showing drives as \"Detected\"](./2024-04-23_07-43.png).\n\n- Steven went into the lab and snapped some pics:\n\n### Expansion unit has no power:\n\n![Expansion unit has no power](./IMG_6545.jpg)\n\n---\n\n### UPS is off:\n\n![UPS is off](./IMG_6547.jpg)\n\n---\n\n- Steven was unable to resolve the problem with the UPS, so plugged the expansion unit into the functional UPS and powered the expansion unit on.\n\nThis resolved everything. Synology Storage Manager immediately recognized that the expansion unit was connected again, and prompted me with a message to re-assemble the Storage Pool. This process took barely a minute and Gannet was back in action!\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}